name: Apigee Proxy Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_proxy:
    name: Deploy Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process form data
        run: |
          echo "Proxy Name: ${{ github.event.inputs.ProxyName }}"
          echo "Base Path: ${{ github.event.inputs.BasePath }}"
          echo "URL: ${{ github.event.inputs.Url }}"

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # - name: Build and Deploy Proxy
      #   env:
      #     PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      #     PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
      #     PROXY_NAME: ${{ secrets.PROXY_NAME }}
      #     ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      #   run: |
      #     mvn -f pom.xml install -Ptest -Dusername="$PROXY_USERNAME" -Dpassword="$PROXY_PASSWORD" -Dproxyname="$PROXY_NAME" -Denvironment="$ENVIRONMENT"
