name: Form Submission Workflow

on:
  repository_dispatch:
    types:
      - form_submission

jobs:
  print_form_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Form Data
        run: |
          echo "Received form submission:"
          echo "Proxy Name: ${{ github.event.client_payload.ProxyName }}"
          echo "Base Path: ${{ github.event.client_payload.BasePath }}"
          echo "URL: ${{ github.event.client_payload.Url }}"
