name: Form Submission

on:
  repository_dispatch:
    types: [form_submission]

jobs:
  process_form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print form data
        run: |
          echo "Proxy Name: ${{ github.event.client_payload.ProxyName }}"
          echo "Base Path: ${{ github.event.client_payload.BasePath }}"
          echo "URL: ${{ github.event.client_payload.Url }}"
